version: "3.9"

services:

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,lambda,iam
      - PORT_WEB_UI=8080
      - EAGER_SERVICE_LOADING=1
    ports: 
      - '4566-4583:4566-4583'
      - "8080:8080"
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
